post_install() {
  /usr/lib/ryotunes-v2.2/activate-replacement || return 1
}

post_upgrade() {
  /usr/lib/ryotunes-v2.2/activate-replacement || return 1
}

pre_remove() {
  /usr/lib/ryotunes-v2.2/deactivate-replacement || true
}

post_remove() {
  rm -rf /var/lib/ryotunes-v2.2
  if command -v update-desktop-database >/dev/null 2>&1; then
    update-desktop-database /usr/share/applications >/dev/null 2>&1 || true
  fi
}
